use_frameworks!

platform :ios, '8.0'

target 'YLBbarrage_Example' do
  pod 'YLBbarrage', :path => '../'

  target 'YLBbarrage_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
